// Auto-generated by scripts/migrate-wp.ts — do not edit manually

export interface CategoryConfig {
  slug: string;
  label: string;
  description: string;
  colorClass: string;
  navPriority: number;
}

export const categories: CategoryConfig[] = [
  {
    "slug": "horoskopi",
    "label": "Horoskopi",
    "description": "Parashikime astrologjike ditore, javore dhe mujore.",
    "colorClass": "bg-purple-600 text-white",
    "navPriority": 1
  },
  {
    "slug": "kuriozitete",
    "label": "Kuriozitete",
    "description": "Fakte interesante dhe informacione nga bota.",
    "colorClass": "bg-amber-600 text-white",
    "navPriority": 2
  },
  {
    "slug": "argetim",
    "label": "Argëtim",
    "description": "Artikuj argëtues, humor dhe përmbajtje e lehtë.",
    "colorClass": "bg-primary text-white",
    "navPriority": 3
  },
  {
    "slug": "personale",
    "label": "Zhvillim Personal",
    "description": "Këshilla për rritje personale, produktivitet dhe sukses.",
    "colorClass": "bg-teal-600 text-white",
    "navPriority": 4
  },
  {
    "slug": "udhetime",
    "label": "Udhëtime",
    "description": "Destinacione, këshilla udhëtimi dhe vende të bukura.",
    "colorClass": "bg-sky-600 text-white",
    "navPriority": 5
  },
  {
    "slug": "lifestyle",
    "label": "Lifestyle",
    "description": "Moda, stili i jetës, trende dhe mirëqenie.",
    "colorClass": "bg-sage text-white",
    "navPriority": 6
  },
  {
    "slug": "grate-shqiptare",
    "label": "Gratë Shqiptare",
    "description": "Histori frymëzuese të grave shqiptare në botë.",
    "colorClass": "bg-charcoal text-white",
    "navPriority": 7
  },
  {
    "slug": "dashuri",
    "label": "Dashuri & Takime",
    "description": "Këshilla për dashurinë, marrëdhëniet dhe takimet.",
    "colorClass": "bg-warm-rose text-white",
    "navPriority": 8
  },
  {
    "slug": "letersi",
    "label": "Letërsi & Poezi",
    "description": "Letërsia shqipe, poezi dhe tregime frymëzuese.",
    "colorClass": "bg-terracotta text-white",
    "navPriority": 9
  },
  {
    "slug": "tv-shqip",
    "label": "TV Shqip",
    "description": "Kanalet shqiptare live dhe programe televizive.",
    "colorClass": "bg-red-600 text-white",
    "navPriority": 10
  },
  {
    "slug": "moti",
    "label": "Parashikimi i Motit",
    "description": "Parashikimi i motit për qytetet shqiptare.",
    "colorClass": "bg-blue-500 text-white",
    "navPriority": 11
  },
  {
    "slug": "te-ndryshme",
    "label": "Të Ndryshme",
    "description": "Artikuj të ndryshëm mbi tema të larmishme.",
    "colorClass": "bg-gray-600 text-white",
    "navPriority": 12
  }
];

export type Category = string;

export const categoryMap = new Map(categories.map((c) => [c.slug, c]));

export function getCategoryConfig(slug: string): CategoryConfig | undefined {
  return categoryMap.get(slug);
}

export const categoryLabels: Record<string, string> = Object.fromEntries(
  categories.map((c) => [c.slug, c.label])
);

export const categoryColors: Record<string, string> = Object.fromEntries(
  categories.map((c) => [c.slug, c.colorClass])
);

export const navCategories = categories
  .filter((c) => c.navPriority <= 6)
  .sort((a, b) => a.navPriority - b.navPriority);

export const moreCategories = categories
  .filter((c) => c.navPriority > 6)
  .sort((a, b) => a.navPriority - b.navPriority);
